# Generated by Django 5.0.14 on 2025-09-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tableclearflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PunchData',
        ),
    ]
