# Generated by Django 5.0.14 on 2025-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_punchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_settings',
            name='auto_man',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter_settings',
            name='timer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
