# Generated by Django 5.0.14 on 2025-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parameter_settings_auto_man_parameter_settings_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_settings',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
